# Header
menu:
  闯前端: /works
  享阅读: /
  来切磋: /about
  爱摄影: /instagram
  # 随笔: /tags/随笔

# SubNav
subnav:
  weibo: "http://weibo.com/lishangmou"
  github: "https://github.com/luuman"
  zhihu: "https://www.zhihu.com/people/luuman"
  mail: "512769206@qq.com"
  google: "http://i.youku.com/shangmou"
  rss: /atom.xml
  twitter: "http://twitter.com/luuman"
  facebook: "#"
  #linkedin: "https://www.linkedin.com/in/%E5%BF%A0%E6%88%90-%E6%9D%8E-a48562b1"
  #douban: "#"
  #google: "#"
  #zhihu: "zhihu"
  #douban: "douban"
  #Facebook: "#"
  #Google: "#"
  #Twitter: "#"
  #LinkedIn: "#"
  #QQ: "#"
  #微信: "Wechat"
  #PayPal: "#"
  #StackOverflow: "#"
  #Instagram: "#"
  #Flickr: "#"
  
  #fa-weibo: "http://weibo.com/lishangmou"
  #fa-github: 
  #fa-linkedin:
  #fa-Instagram:
  #fa-rss: 
  #fa-twitter:
  #fa-facebook:
  #fa-google:
  #fa-mail:
  #fa-stackoverflow:
  
# "5": show images form bg-1.jpg to bg-5.jpg in `/yelee/source/background/`
# "5": 显示`/yelee/source/background/`文件夹中 bg-1.jpg 到 bg-5.jpg 这5张图片
# "0": white-gray background | 淳朴灰白背景
# background_image: 1

# Content
excerpt_link: 大航海 #修改more>>的文字
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
#google_analytics: ''
baidu_analytics: true
favicon: /img/favicon.png

#你的头像url
avatar: "/img/head.jpg"

#是否开启分享
share: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key（http://duoshuo-key.duoshuo.com/）
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: luuman

#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  MOxFIVE: http://MOxFIVE.github.io/
  dengo: http://dengo.org/
  Litten: http://litten.github.io/
  DoubleV: http://www.vsay.cn/
  兮兮: http://www.ccwebsite.com/
  翁天信: http://blog.dandyweng.com/
  潘利强: http://www.plqblog.com/views/index.php
  PuYart: http://puyart.net/

swift_search:
  enable: true

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 纠棱厚，海贼控；爱代码，强迫症；常熬夜，闹酩掰；人生短，逛今宵。